### ISSUE TITLE
can we make the background color to transparent ?

### ISSUE THREAD

**Issue by mustafa-707** [Mapventure/statusbarz#6]
Hello , 
 Can we make the background color to transparent always , because I use this plugin with a fully scrolled screen.
 
 Thanks

**Comment by O-Hannonen** [comment]
What do you mean with transparent background? Could you provide a screenshot or any other form of clarification of what you would like to achieve and what the issue is?  @mustafa-707

**Comment by mustafa-707** [comment]
![284099150_1078301013033915_8853221002571959044_n](https://user-images.githubusercontent.com/74349843/170823377-22de71a3-8c0a-4108-a106-18de4d13955c.jpg)

The background is white in here

**Comment by O-Hannonen** [comment]
On android, the background is always transparent, and the only thing we're changing is the icon colors (brightness). Are you sure nothing else is changing the color? For instance AnnotatedRegion or AppBar? What device and android version are you running on? Could you provide a minimal reproducible example of the issue. Note: we're just about to release a new version of the plugin which allows developers to play a lot more with the colors etc.

**Comment by mustafa-707** [comment]
oh sorry , I was try to ensure that my code is not force to make the color white , but it looks the `SafeArea` Widget makes the color white , So I will close the issue ,

Thank you for your time , and thanks for this useful package
