### ISSUE TITLE
null check 报错

### ISSUE THREAD

**Issue by DeliriousLee** [Mapventure/statusbarz#7]
final window = WidgetsBinding.instance.window ;
        final mediaQuery = MediaQueryData.fromWindow(window);
WidgetsBinding.instance.window可能为空，MediaQueryData.fromWindow()
出错

**Comment by O-Hannonen** [comment]
In older versions of flutter WidgetsBinding.instance was nullable, but in a recent update it has become non nullable, so the null checks were deleted. Closing this issue for now, since there is no issue.
