### ISSUE TITLE
I want to change the color of the statusbar to match the color of a certain point.

### ISSUE THREAD

**Issue by jtaxiexpress** [Mapventure/statusbarz#8]
<img width="363" alt="スクリーンショット 2022-11-13 12 43 33" src="https://user-images.githubusercontent.com/86914073/201505226-b5da7341-7a91-448f-9b91-fd770145e42b.png">

What I want to do is to get the color of the area directly below the statusbar and dynamically change the color of this red area.
In this case I want the red area to be white.

If I scroll down and come to the blue part, I want to change it from white to blue.
Is it possible to do that?

**Comment by O-Hannonen** [comment]
You can make the statusbar background completely invisible and the icons dark. The dark icons will be visible on both the white and the light blue. To do this with statusbarz, you must set `StatusbarzTheme` inside `StatusbarzCapturer`, or call:

```
Statusbarz.instance.setTheme(
      StatusbarzTheme(
        darkStatusBar: SystemUiOverlayStyle(
          statusBarColor: Colors.transparent,
          statusBarBrightness: Brightness.dark,
        ),
      ),
    );
```

NOTE: this example `SystemUiOverlayStyle` only contains the parameters to change the color on IOS.

After providing proper styling, you can call `Statusbarz.instance.setDarkStatusBar()` to apply the changes. 
Feel free to reopen the issue if you need further assistance.
