### ISSUE TITLE
Update image to version ^4.0.8

### ISSUE THREAD

**Issue by JeromeGsq** [Mapventure/statusbarz#9]
Hi, 

Can you update image from the pubspec.yaml to version 4.0.8 please ? 
I have a conflict between statusbarz and crop_your_image.

Thanks !

![image](https://user-images.githubusercontent.com/6270529/211584539-2c430b2a-299a-4ae1-b6de-d9175cea4b07.png)

**Comment by changweihua** [comment]
Is there any plans about adapted to image 4.*, Thanks

**Comment by O-Hannonen** [comment]
Sorry for the delay, just publishing a new version.
